version: "3.3"
services:
    www:
        build: .
        ports: 
            - "8080:80"
        volumes:
            - ../www:/var/www/html
        links:
            - db
        networks:
          static-network:
            ipv4_address: 172.20.1.1
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'user'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'test'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'test'
        ports:
        # <Port exposed> : < MySQL Port running inside container>
        - '3306:3306'
        expose:
        # Opens port 3306 on the container
        - '3306'
        # Where our data will be persisted
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
          static-network:
            ipv4_address: 172.20.1.2
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
volumes:
    persistent:
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
