version: "3.3"
services:
    www:
        build: .
        ports: 
            - "8080:80"
        volumes:
            - ../www:/var/www/html
            - ./conf/apache/sites/:/etc/apache2/sites-enabled/
        links:
            - db
        networks:
          static-network:
            ipv4_address: 172.20.1.1
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'test'
            MYSQL_ROOT_PASSWORD: 'test'
        ports:
        - '3306:3306'
        expose:
        - '3306'
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf/mysql:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
          static-network:
            ipv4_address: 172.20.1.2
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
volumes:
    persistent:
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
