version: "3.3"
services:
    www:
        build: .
        ports: 
            - "8080:80"
        volumes:
            - ../www:/var/www/html
            - ./conf/apache/php/php.ini:/usr/local/etc/php/php.ini
            - ./conf/apache/php/99-custom.ini:/usr/local/etc/php/conf.d/99-custom.ini
            - ./conf/apache/sites/:/etc/apache2/sites-enabled/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'open_library'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'test'
            MYSQL_ROOT_PASSWORD: 'test'
        ports:
        - '3306:3306'
        expose:
        - '3306'
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf/mysql:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        networks:
            - default
    composer_installation:
        container_name: composer
        image: composer
        volumes:
            - ../www/open-library:/app
        command: composer install --ignore-platform-reqs
volumes:
    persistent: